branches:
  main:
    next-version: 1.0
    tag: ''
    increment: inherit
    source-branches:
      - develop
      - release
      - feature
      - hotfix
    is-release-branch: true
  feature:
    increment: Minor
    tag: alpha
  release:
    increment: Minor
    tag: beta
    is-release-branch: false
  hotfix:
    increment: Patch
    tag: beta
ignore:
  sha: [ ]