mode: Mainline
branches:
  main:
    tag: ''
    increment: inherit
    source-branches:
      - main
    is-release-branch: true
  feature:
    increment: Minor
    tag: alpha
  release:sd
    increment: Minor
    tag: beta
    is-release-branch: false
  hotfix:
    increment: Patch
    tag: beta
ignore:
  sha: [ ]