name: nuget-build-deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: 6.0.x         
    - name: Install dotnet tool manifest
      run: dotnet new tool-manifest
    - name: Install dotnet cake 
      run: dotnet tool install Cake.Tool
    - name: Run cake
      run: dotnet dotnet-cake 
