name: nuget-build-deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
          dotnet-version: 8.0.x 
    - name: Check out Code
      uses: actions/checkout@v4

    - name: Run the Cake script
      uses: cake-build/cake-action@v2
      with:
          arguments: |
            nuget_api_key: ${{ secrets.NUGET_API_KEY }}
            github_token: ${{ github.token }}
            configuration: Release
   