name: nuget-build-deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: 6.0.x 
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.13
      with:
          versionSpec: '5.x'
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.13
      with:
        useConfigFile: true      
        configFilePath: .github/GitVersion.yml
    - name: Check out Code
      uses: actions/checkout@v2
      with:
         fetch-depth: 0
    - name: Run cake
      shell : bash
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        dotnet new tool-manifest
        dotnet tool install Cake.Tool
        dotnet tool restore
        dotnet cake